global:
    scrape_interval: 10s
    evaluation_interval: 10s
    
scrape_configs:
       
    - job_name: 'record-user-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['record-user-swipes-server:8080']
          labels:
            application: 'Record user service app'
            
    - job_name: 'process-user-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['process-user-swipes-server:8081']
          labels:
            application: 'Process user service app'
            
    - job_name: 'kafka-process-attendance'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['kafka-listener-swipes-server:8082']
          labels:
            application: 'Kafka process attendance app'