apiVersion: v1
kind: Service
metadata:
  name: eureka-naming-server
spec:
  selector:
    app: eureka-naming-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      
---------------
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
  
-----------------
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-server-service
spec:
  selector:
    app: api-gateway-server
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
  type: LoadBalancer

--------------------
apiVersion: v1
kind: Service
metadata:
  name: my-sql-server-service
spec:
  selector:
    app: my-sql-server
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  
----------------------
apiVersion: v1
kind: Service
metadata:
  name: record-user-swipes-server-service
spec:
  selector:
    app: record-user-swipes-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

-----------------------
apiVersion: v1
kind: Service
metadata:
  name: process-user-swipes-server-service
spec:
  selector:
    app: process-user-swipes-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
  
-----------------------
apiVersion: v1
kind: Service
metadata:
  name: kafka-listener-swipes-server-service
spec:
  selector:
    app: kafka-listener-swipes-server
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
  
-------------------------
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-server-service
spec:
  selector:
    app: zookeeper-server
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP
  
-------------------------
apiVersion: v1
kind: Service
metadata:
  name: kafka-server-service
spec:
  selector:
    app: kafka-server
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
  
-------------------------
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-service
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
  
-------------------------
apiVersion: v1
kind: Service
metadata:
  name: grafana-server-service
spec:
  selector:
    app: grafana-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer